name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint --workspaces --if-present

      - name: Build
        run: npm run build --workspaces --if-present

      - name: Test
        run: npm run test --workspaces --if-present
